#!/usr/bin/env python3
from gate_common import ROOT,require,main_guard
def verify():
 b=(ROOT/'BUILD_AUDIT.md').read_text(encoding='utf-8'); c=(ROOT/'changelog.md').read_text(encoding='utf-8'); r=(ROOT/'rules/PROJECT_RULES.md').read_text(encoding='utf-8')
 require(b.startswith('# OpenGLESScope 3.0.7 release audit'),'build audit identity drift')
 for x in ['Version 3.0.7 / 3007','Database 3.0.26','VulkanScope 3.0.12','EGL','report','Database']:
  require(x.lower() in b.lower(),'build audit missing: '+x)
 require(c.startswith('# OpenGLESScope 3.0.7'),'changelog identity drift')
 require('## Release 2.2.1 Kotlin/Compose parity compile-correctness hotfix' in r,'2.2.1 rules section missing')
 require((ROOT/'tools/verify_2_2_1_kotlin_compile_hotfix.py').is_file(),'2.2.1 compile verifier missing')
 require((ROOT/'rules/2.2.1_KOTLIN_COMPOSE_COMPILE_HOTFIX_AUDIT.md').is_file(),'2.2.1 compile audit missing')
 require('## Release 2.2.2 VulkanScope video-detail parity audit' in r,'2.2.2 video parity rules section missing')
 require((ROOT/'tests/golden/2_2_2_video_ui_parity_regression_contract.json').is_file(),'2.2.2 predecessor hash census absent')
 require((ROOT/'rules/2.2.2_VULKANSCOPE_VIDEO_UI_PARITY_AUDIT.md').is_file(),'new video evidence audit absent')
 require('## Release 2.2.3 full branding/copy/HDR/extension interaction parity audit' in r,'2.2.3 rules missing')
 require((ROOT/'rules/2.2.3_BRANDING_HDR_EXTENSION_PARITY_AUDIT.md').is_file(),'2.2.3 audit missing')
 require((ROOT/'tests/golden/2_2_3_full_ui_regression_contract.json').is_file(),'2.2.3 regression census missing')
 require('## Release 2.2.4 paging/Analysis/status/report source parity audit' in r,'2.2.5 release rules missing')
 require((ROOT/'tests/golden/2_2_4_paging_analysis_report_regression_contract.json').is_file(),'2.2.5 hash contract missing')
 require((ROOT/'rules/2.2.4_VULKANSCOPE_PAGING_ANALYSIS_REPORT_PARITY_AUDIT.md').is_file(),'2.2.5 audit missing')
 require('## Release 2.2.5 input, File Manager and responsive accessibility parity audit' in r,'2.2.5 rules missing')
 require((ROOT/'tests/golden/2_2_5_desktop_accessibility_regression_contract.json').is_file(),'current hash contract missing')
 require((ROOT/'rules/2.2.5_INPUT_LAYOUT_ACCESSIBILITY_PARITY_AUDIT.md').is_file(),'2.2.5 evidence audit missing')
 require('## Release 2.2.6 real Kotlin compile correction and UI parity re-audit' in r,'historical 2.2.6 release rules missing')
 require('## Release 2.2.7 official artwork, reference evidence menu, overlay and full-screen File Manager audit' in r,'2.2.7 release rules missing')
 require((ROOT/'rules/2.2.7_EGL_EXTENSION_FILE_MANAGER_PARITY_AUDIT.md').is_file(),'2.2.7 audit missing')
 require((ROOT/'tests/golden/2_2_7_reference_ui_regression_contract.json').is_file(),'2.2.7 immutable predecessor contract missing')
 require((ROOT/'rules/2.2.6_KOTLIN_BUILD_AND_PARITY_AUDIT.md').is_file(),'2.2.7 audit missing')
 require((ROOT/'tests/golden/2_2_0_vulkanscope_common_drawable_hashes.json').is_file(),'2.2.0 common drawable census missing')
 require('## Release 2.2.8 full-logo, continuous blur, SDK 37.2 and Encyclopedia search parity audit' in r,'2.2.8 release contract missing')
 require((ROOT/'rules/2.2.8_BRANDING_BLUR_SDK_ENCYCLOPEDIA_AUDIT.md').is_file(),'2.2.8 engineering audit missing')
 require((ROOT/'tests/golden/2_2_8_release_regression_contract.json').is_file(),'2.2.8 immutable predecessor evidence missing')
 require('## Release 2.2.9 File Manager, Khronos, viewport and brand alignment parity' in r,'2.2.9 rules section missing')
 require((ROOT/'tests/golden/2_2_9_release_regression_contract.json').is_file(),'2.2.9 source hash contract missing')
 require('## Release 2.2.10 license, Extensions evidence, File Manager chooser, Database and GPU detail correction' in r,'2.2.10 engineering rules missing')
 require((ROOT/'tests/golden/2_2_10_release_regression_contract.json').is_file(),'2.2.10 exact predecessor hash census missing')
 require((ROOT/'rules/2.2.10_LICENSE_EXTENSION_FILEMANAGER_DATABASE_GPU_AUDIT.md').is_file(),'2.2.10 evidence audit missing')
 require('## Release 2.2.11 license scroll arrows, shared storage feedback and submit affordance correction' in r,'2.2.11 rules missing')
 require((ROOT/'tests/golden/2_2_11_release_regression_contract.json').is_file(),'2.2.11 SHA predecessor inventory missing')
 require('## Release 2.2.12 reference Extension Details, Database submission, trademark and cold-start timing correction' in r,'2.2.12 rules missing')
 require((ROOT/'tests/golden/2_2_12_release_regression_contract.json').is_file(),'2.2.12 source contract missing')
 require('## Release 2.2.13 VulkanScope-equivalent Database failure log dialog audit' in r,'2.2.13 engineering rules missing')
 require((ROOT/'tests/golden/2_2_13_release_regression_contract.json').is_file(),'2.2.13 source contract missing')
 require('## Release 2.2.14 VulkanScope update-transfer and Database report-list parity' in r,'2.2.14 rules missing')
 require((ROOT/'tests/golden/2_2_14_release_regression_contract.json').is_file(),'2.2.14 source inventory missing')
 require('## Release 2.2.15 complete evidence-integrity / current-registry audit' in r,'2.2.15 rules missing')
 require((ROOT/'tests/golden/2_2_15_release_regression_contract.json').is_file(),'2.2.15 source lock missing')
 require('## Release 2.2.16 validated-network and bottom navigation parity' in r,'2.2.16 rules missing')
 require((ROOT/'tests/golden/2_2_16_release_regression_contract.json').is_file(),'2.2.16 source lock missing')
 require('## Release 2.2.17 Kotlin TextUnit compile hotfix' in r,'2.2.17 rules missing')
 require((ROOT/'tests/golden/2_2_17_release_regression_contract.json').is_file(),'2.2.17 source lock missing')
 require((ROOT/'rules/2.2.17_KOTLIN_TEXTUNIT_COMPILE_HOTFIX_AUDIT.md').is_file(),'2.2.17 compile audit missing')
 require('## Release 2.2.18 notification-state and EGL identity provenance audit' in r,'historical 2.2.18 rules missing')
 require((ROOT/'tests/golden/2_2_18_release_regression_contract.json').is_file(),'2.2.19 regression contract missing')
 require((ROOT/'rules/2.2.18_NOTIFICATION_EGL_PROVENANCE_AUDIT.md').is_file(),'2.2.19 audit missing')
 require('## Release 2.2.19 specification, memory and performance correction' in r,'2.2.19 rules missing')
 require((ROOT/'tests/golden/2_2_19_release_regression_contract.json').is_file(),'2.2.19 contract missing')
 require((ROOT/'rules/2.2.19_SPEC_MEMORY_PERFORMANCE_AUDIT.md').is_file(),'2.2.19 audit missing')
 require('## Release 2.2.20 EGL query and bounded DMA-BUF report integrity' in r,'historical 2.2.20 rules missing')
 require('## Release 2.2.21 GPU card, navigation and official EGL brand variants' in r,'current 2.2.21 rules missing')
 require((ROOT/'tests/golden/2_2_20_release_regression_contract.json').is_file(),'inherited predecessor inventory missing')
 require((ROOT/'tests/golden/2_2_21_release_regression_contract.json').is_file(),'current predecessor inventory missing')
 require((ROOT/'rules/2.2.20_EGL_QUERY_DMA_REPORT_SECURITY_AUDIT.md').is_file(),'inherited security/report audit missing')
 require((ROOT/'rules/2.2.21_GPU_NAV_BRANDING_AUDIT.md').is_file(),'current UI/GPU identity audit missing')
 require('## Release 2.2.22 VulkanScope evidence-column and long-hold parity + native/report security audit' in r,'2.2.22 rules missing')
 require((ROOT/'tests/golden/2_2_22_release_regression_contract.json').is_file(),'2.2.22 predecessor hash contract missing')
 require((ROOT/'rules/2.2.22_EVIDENCE_LAYOUT_INTEGRITY_AUDIT.md').is_file(),'2.2.22 audit missing')
if __name__=='__main__': main_guard('verify_release_docs',verify)

# 2.2.21 inherits the immutable 2.2.20 security and EGL query evidence, and adds UI/GPU branding rules.
